baseURL = "https://www.balajisivaraman.com/"
languageCode = "en-us"
title = "Balaji Sivaraman"

# Enable Chroma Syntax Highlighting
pygmentsOptions = "linenos=true"
pygmentsStyle = "solarized-light"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
