baseURL = "https://www.balajisivaraman.com/"
languageCode = "en-us"
title = "Balaji Sivaraman"

# Enable Chroma Syntax Highlighting
pygmentsOptions = "linenos=true"
pygmentsStyle = "solarized-light"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true

preserveTaxonomyNames = true

[permalinks]
post = "/:year/:month/:day/:slug"

[params]
author = "Balaji Sivaraman"
description = "I blog mostly about programming, specifically in statically typed languages."
